

CONST_H = 173
CONST_M = 60
CONST_STEPS = 10000
CONST_TIME = 60
CONST_ENERGY = 0.035*CONST_M+((CONST_STEPS/CONST_TIME)**2 / CONST_H) * 0.029*CONST_M
print(f"Каллорий сожжено {CONST_ENERGY}; Пройденная дистанция: {CONST_STEPS*(CONST_H/4+0.37)/CONST_TIME}")
